export const dataSections = [
  {
    id: 1,
    name: "fish",
    description: "Delicious Italian pasta ",
    imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "",
        isActive: false,
      },
      {
        id: 3,
        name: "apaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "",
        isActive: true,
      },
      {
        id: 4,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo",
        imageUrl: "",
        isActive: false,
      },
    ],
  },

  {
    id: 2,
    name: "Pizza",
    description: "Cheesy and crispy pizza",
    imageUrl: "https://via.placeholder.com/150",
    isActive: false,
    items: [
      {
        id: 3,
        name: "Margherita Pizza",
        price: 10.0,
        description: "Classic pizza with tomato and cheese",
        imageUrl: "https://via.placeholder.com/200",
        isActive: false,
      },
      {
        id: 4,
        name: "Pepperoni Pizza",
        price: 15.0,
        description: "Pizza topped with pepperoni slices",
        imageUrl: "https://via.placeholder.com/200",
        isActive: false,
      },
    ],
  },
  {
    id: 3,
    name: "Appatizers",
    description: "Delicious Italian pasta",
    // imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 4,
    name: "Rice",
    description: "Delicious Italian pasta",
    imageUrl: "",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 5,
    name: "سندوتشات",
    description: " سندوتشات جميع",
    // imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 6,
    name: "Salad",
    description: "Fruit Salad ",
    imageUrl: "",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 7,
    name: "Meat",
    description: "Meat ",
    // imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 8,
    name: "No Item",
    description: "No",
    // imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 9,
    name: "Sandwatchs",
    description: "All Sandwatchs",
    // imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "Spaghetti Pasta",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "Fettuccine Alfredo",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 11,
    name: "Cola",
    description: "Pepsi ",
    imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [],
  },
  {
    id: 12,
    name: "Soup",
    description: "Soup",
    imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [],
  },
  {
    id: 10,
    name: "Tea",
    description: "Tea",
    imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [],
  },
  {
    id: 100,
    name: "Coffe",
    description: "Coffe",
    imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "coffe",
        price: 12.5,
        description: "coffe",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "coffe",
        price: 13.0,
        description: "coffe",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
  {
    id: 140,
    name: "اسماك",
    description: "اسماك",
    // imageUrl: "https://via.placeholder.com/150",
    isActive: true,
    items: [
      {
        id: 1,
        name: "اسماك",
        price: 12.5,
        description: "Creamy pasta with bacon",
        imageUrl: "https://via.placeholder.com/200",
        isActive: true,
      },
      {
        id: 2,
        name: "اسماك",
        price: 13.0,
        description: "Pasta with creamy Alfredo sauce",
        imageUrl: "https://via.placeholder.com/p",
        isActive: false,
      },
    ],
  },
];
